services:
  - type: web
    name: evm-realtimechat-server
    runtime: node
    plan: free
    buildCommand: pnpm i && pnpm build
    startCommand: pnpm run start
    envVars:
      - key: VITE_DEV_STATUS
        value: 3